// Mocks generated by Mockito 5.4.6 from annotations
// in akora_app/test/ai_api_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:akora_app/core/services/ai_api_service.dart' as _i2;
import 'package:dart_openai/dart_openai.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AiApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiApiService extends _i1.Mock implements _i2.AiApiService {
  MockAiApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> getChatResponse(
    List<_i4.OpenAIChatCompletionChoiceMessageModel>? messages,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getChatResponse, [messages]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#getChatResponse, [messages]),
              ),
            ),
          )
          as _i3.Future<String>);
}
